import DOMPurify from 'dompurify';
import type { Transformer } from './types';
// import { diff } from '@/utils/diff';

const DOCTYPE_XHTML11 = `<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.1//EN"
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">`;

export const sanitizerTransformer: Transformer = {
  name: 'sanitizer',

  transform: async (ctx) => {
    const allowScript = ctx.viewSettings.allowScript;
    if (allowScript) return ctx.content;

    const result = ctx.content.replaceAll('&nbsp;', '&#160;');

    const sanitized = DOMPurify.sanitize(result, {
      WHOLE_DOCUMENT: true,
      FORBID_TAGS: ['script', 'iframe', 'object', 'embed'],
      FORBID_ATTR: ['srcdoc'],
      ALLOWED_URI_REGEXP:
        /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|sms|cid|xmpp|blob|data):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i,
      // `none` is MathML's empty-slot placeholder. A book that writes
      // `<mmultiscripts><mprescripts/><none/><mi>k</mi>…` needs it to keep the
      // pre-script sub/superscript pairs aligned; dropping it moves `k` into the
      // wrong slot and the formula silently renders as a different one. DOMPurify
      // leaves it out of its default `mathMl` allow-list, but it *is* in the
      // `mathMlDisallowed` list that feeds the namespace check, so re-allowing it
      // by name is enough (and it is an empty element, so nothing else rides in
      // with it).
      //
      // `semantics` / `annotation` / `annotation-xml` are deliberately NOT added
      // here. Allowing the first two does not stop the duplication — the
      // sanitizer's unwrap is replaced by the engine printing the annotation text
      // anyway — and allowing `annotation-xml` would let its `encoding` attribute
      // survive (it is in DOMPurify's default MathML attribute list), putting the
      // `encoding="text/html"` HTML-integration-point path back in the DOM. All
      // three are reduced by the `mathml` transformer instead, which also runs on
      // the `allowScript` path this sanitizer skips.
      ADD_TAGS: ['link', 'meta', 'none'],
      ADD_ATTR: (attributeName: string) => {
        const attrWhitelist = [
          'xmlns',
          'http-equiv',
          'content',
          'charset',
          'link',
          'vlink',
          'imt-state', // custom attribute generated by some translators
          'data-wr-footernote', // custom attribute for weread footnotes
          'zy-footnote', // custom attribute for zhangyue footnotes
          'cfi-inert', // custom attribute to mark nodes as inert for CFI processing
          'cfi-skip', // custom attribute to mark nodes to be skipped in CFI processing
        ];
        return (
          attrWhitelist.includes(attributeName) ||
          attributeName.startsWith('xml:') ||
          attributeName.startsWith('xmlns:') ||
          attributeName.startsWith('epub:')
        );
      },
      RETURN_DOM: true,
    });

    const serializer = new XMLSerializer();
    let serialized = serializer.serializeToString(sanitized);
    serialized = serialized.replaceAll('&#160;', '&nbsp;').replaceAll('\u00A0', '&nbsp;');
    serialized = '<?xml version="1.0" encoding="utf-8"?>' + DOCTYPE_XHTML11 + serialized;
    serialized = serialized.replace(/(<head[^>]*>)/i, '\n$1');
    serialized = serialized.replace(/(<\/body>)(<\/html>)/i, '$1\n$2');

    // console.log(`Sanitizer diff:\n${diff(result, serialized)}`);

    return serialized;
  },
};
